/**
 * Shared cable-construction types + material palette.
 *
 * The data itself lives in public/content/cable_specs.json and is
 * generated by scripts/generate_cable_art.py — the same script that
 * draws the era thumbnails. Edit the spec there, re-run the script,
 * and the thumbnails, cross-sections and animation all move together.
 */

export interface Material {
  fill: string
  edge: string
  hi: string
  name: string
}

export interface CableLayer {
  label: string
  material: string
  r: number
  pattern: 'solid' | 'armour' | 'braid' | 'foil' | 'weave' | 'foam'
  note: string
}

export interface CableConnector {
  kind: string
  label: string
  note: string
}

export interface CableChip {
  label: string
  role: string
  note: string
}

export interface CableSpec {
  family: string
  tagline: string
  signal: { kind: SignalKind; label: string; speed: number }
  layers: CableLayer[]
  connectors: CableConnector[]
  chips: CableChip[]
  cores?: { count: number; material: string; r: number; ring: number; row?: boolean; twist?: boolean }
  pairs?: { count: number; colors: string[]; ring: number; r: number; twist?: boolean }
  bundle?: { label: string; material: string; cx: number; cy: number; r: number; pair?: boolean; shielded?: boolean }[]
}

export type SignalKind = 'current' | 'differential' | 'rf' | 'light' | 'audio'

export const MATERIALS: Record<string, Material> = {
  copper: { fill: '#b87333', edge: '#8a5524', hi: '#e8913a', name: 'Copper' },
  'copper-lit': { fill: '#e8913a', edge: '#b86b22', hi: '#ffc98a', name: 'Copper' },
  tinned: { fill: '#c3ccd8', edge: '#8d97a4', hi: '#e8eef5', name: 'Tinned copper' },
  steel: { fill: '#9aa7b4', edge: '#6d7884', hi: '#c9d4de', name: 'Steel' },
  iron: { fill: '#7d8894', edge: '#586471', hi: '#a7b2bd', name: 'Iron' },
  gutta: { fill: '#6b4f2a', edge: '#4a3619', hi: '#8f6d3d', name: 'Gutta-percha' },
  hemp: { fill: '#8a6b45', edge: '#5f4930', hi: '#ab8a60', name: 'Tarred hemp' },
  jute: { fill: '#7e6a48', edge: '#584a33', hi: '#a08a63', name: 'Jute serving' },
  rubber: { fill: '#2c2c30', edge: '#161618', hi: '#45454b', name: 'Rubber' },
  cotton: { fill: '#b9ae95', edge: '#8b8170', hi: '#d8cfba', name: 'Cotton braid' },
  paper: { fill: '#a9a08c', edge: '#7d7566', hi: '#cbc3b1', name: 'Paper' },
  pe: { fill: '#22303f', edge: '#14202c', hi: '#35485c', name: 'Polyethylene' },
  'foam-pe': { fill: '#2b3b4c', edge: '#1a2735', hi: '#3f556d', name: 'Foamed PE' },
  pvc: { fill: '#1b2531', edge: '#0e1620', hi: '#2c3a4a', name: 'PVC jacket' },
  lszh: { fill: '#1d2a2a', edge: '#101a1a', hi: '#2e4242', name: 'LSZH jacket' },
  teflon: { fill: '#2a3646', edge: '#18212c', hi: '#3d4c60', name: 'FEP insulation' },
  foil: { fill: '#c7d2da', edge: '#94a1ab', hi: '#e6eef4', name: 'Foil shield' },
  braid: { fill: '#8b98a8', edge: '#5f6b79', hi: '#b6c2cf', name: 'Braided shield' },
  glass: { fill: '#8fd8e8', edge: '#4f9db0', hi: '#d3f4fb', name: 'Glass core' },
  cladding: { fill: '#3a6b7d', edge: '#25495a', hi: '#5b93a7', name: 'Cladding' },
  coating: { fill: '#244553', edge: '#152e39', hi: '#376a7d', name: 'Acrylate coating' },
  aramid: { fill: '#d9c48a', edge: '#a89660', hi: '#f0e0b0', name: 'Aramid yarn' },
  gel: { fill: '#2f4a52', edge: '#1c3037', hi: '#476b76', name: 'Filling gel' },
  gold: { fill: '#f5d06f', edge: '#c0a047', hi: '#ffeaa8', name: 'Gold contact' },
  silicon: { fill: '#38455c', edge: '#222c3d', hi: '#54658a', name: 'Silicon die' },
  pcb: { fill: '#1f4d3d', edge: '#123024', hi: '#2f7259', name: 'PCB' },
  polymer: { fill: '#4c3a63', edge: '#2f2340', hi: '#6f5690', name: 'Healing polymer' },
  capsule: { fill: '#7fe3c0', edge: '#3f9e82', hi: '#b6f5e0', name: 'Microcapsules' },
  air: { fill: '#0d1420', edge: '#060a12', hi: '#1a2536', name: 'Air gap' }
}

/** What the moving thing actually is, per signal type. */
export const SIGNAL_COPY: Record<SignalKind, { carrier: string; blurb: string; color: string }> = {
  current: {
    carrier: 'Electrons',
    blurb: 'Electrons barely crawl — but the electric field pushing them travels near light speed. That field is the signal.',
    color: '#e8913a'
  },
  audio: {
    carrier: 'Analogue current',
    blurb: 'The current copies the shape of the sound wave. Any noise picked up along the way becomes part of the sound.',
    color: '#f5d06f'
  },
  differential: {
    carrier: 'Differential pulses',
    blurb: 'Each pair carries the same signal twice — once upside down. The receiver subtracts them, and any noise that hit both wires cancels out.',
    color: '#3fbfd4'
  },
  rf: {
    carrier: 'RF wave',
    blurb: 'The wave travels in the gap between centre conductor and shield. Return current flows back along the shield, so the cable barely radiates.',
    color: '#6fd9ea'
  },
  light: {
    carrier: 'Photons',
    blurb: 'Light bounces along inside the core by total internal reflection — it never actually touches the outside world.',
    color: '#8fd8e8'
  }
}
